defmodule DocGenerator.Fixtures do
  @moduledoc """
  Test fixtures for DocGenerator tests.

  Provides sample modules with various characteristics for testing.
  """

  defmodule SimpleModule do
    @moduledoc """
    A simple module for testing basic documentation generation.
    """

    @doc """
    Greets the given name.
    """
    @spec greet(String.t()) :: String.t()
    def greet(name) do
      "Hello, #{name}!"
    end

    @doc """
    Adds two numbers.
    """
    @spec add(number(), number()) :: number()
    def add(a, b) do
      a + b
    end
  end

  defmodule ComplexModule do
    @moduledoc """
    A more complex module with types, callbacks, and multiple functions.
    """

    @type user :: %{name: String.t(), age: non_neg_integer()}
    @type result :: {:ok, term()} | {:error, term()}

    @doc """
    Creates a new user.
    """
    @spec create_user(String.t(), non_neg_integer()) :: user()
    def create_user(name, age) do
      %{name: name, age: age}
    end

    @doc """
    Validates a user struct.
    """
    @spec validate_user(user()) :: result()
    def validate_user(%{name: name, age: age}) when is_binary(name) and is_integer(age) do
      {:ok, %{name: name, age: age}}
    end

    def validate_user(_) do
      {:error, :invalid_user}
    end

    @doc """
    Gets user name.
    """
    @spec get_name(user()) :: String.t()
    def get_name(%{name: name}), do: name
  end

  defmodule BehaviourModule do
    @moduledoc """
    A module that defines a behaviour.
    """

    @callback execute(term()) :: {:ok, term()} | {:error, term()}
    @callback available?() :: boolean()

    @optional_callbacks available?: 0
  end

  defmodule ImplementationModule do
    @moduledoc """
    A module that implements a behaviour.
    """

    @behaviour DocGenerator.Fixtures.BehaviourModule

    @impl true
    def execute(input) do
      {:ok, input}
    end

    @impl true
    def available? do
      true
    end
  end

  @doc """
  Returns sample module info for testing.
  """
  def sample_module_info(module \\ SimpleModule) do
    DocGenerator.ModuleInfo.new(module,
      moduledoc: "A sample module for testing",
      functions: [
        %{
          name: :greet,
          arity: 1,
          type: :def,
          doc: "Greets someone",
          signature: "greet(name)",
          specs: []
        },
        %{
          name: :add,
          arity: 2,
          type: :def,
          doc: "Adds two numbers",
          signature: "add(a, b)",
          specs: []
        }
      ],
      types: [],
      callbacks: [],
      behaviours: []
    )
  end

  @doc """
  Returns a sample project struct.
  """
  def sample_project(path \\ "/tmp/test_project") do
    DocGenerator.Project.new(path,
      name: "TestProject",
      version: "0.1.0",
      modules: [SimpleModule, ComplexModule]
    )
  end

  @doc """
  Returns mock provider result for testing.
  """
  def mock_provider_result(provider \\ :claude) do
    {:ok,
     %{
       content: """
       # Sample Documentation

       This is sample documentation generated by #{provider}.

       ## Functions

       - `greet/1` - Greets a person by name
       - `add/2` - Adds two numbers together

       ## Examples

           iex> greet("World")
           "Hello, World!"
       """,
       provider: provider,
       style: :formal,
       metadata: %{model: "test-model"}
     }}
  end
end
